name: Arron Autopilot
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  run:
    if: contains(github.event.comment.body, '/arron')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse command
        id: parse
        run: |
          BODY="${{ github.event.comment.body }}"
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Respond
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ Arron received: `${{ steps.parse.outputs.BODY }}`
            - Nightly optimize runs at 03:00 UTC.
            - Deploy hook active on push to `main`.
