name: Site health
on:
  schedule:
    - cron: "15 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.13.x
      - name: Run Lighthouse against production
        run: |
          lhci autorun --collect.url=https://www.pleadingsanity.co.uk                        --upload.target=temporary-public-storage
