[build]
  publish = "."
  functions = "netlify/functions"
  command = ""   # no build step for static site; keep empty

# Force SPA-style routing to index.html (keeps your links working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (safe defaults)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "interest-cohort=()"
