name: Optimize & Auto-commit
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC nightly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || npm i
      - name: Run optimizer
        run: npm run optimize
      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "ps-bot"
            git config user.email "bot@pleadingsanity.co.uk"
            git add -A
            git commit -m "chore: nightly optimize"
            git push
          else
            echo "No changes to commit."
          fi
