
name: Deploy to GitHub Pages

# 1) Trigger on every push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 2) Ensure we have a runner
    runs-on: ubuntu-latest

    # 3) Grant the Pages permission
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      # 4) Checkout your code
      - uses: actions/checkout@v3

      # 5) Configure Pages (sets up a .github-pages-deploy dir)
      - uses: actions/configure-pages@v3

      # 6) Upload the entire repo as your site artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      # 7) Deploy to GitHub Pages
      - uses: actions/deploy-pages@v1
