name: Deploy to GitHub Pages

# 1) Trigger on every push to main
on:
  push:
    branches: [ main ]

# 2) Grant only the permissions we need
permissions:
  pages: write    # for deploy-pages@v4
  id-token: write # for configure-pages@v5
  contents: read  # for checkout@v3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 3) Pull down your code
      - name: Checkout
        uses: actions/checkout@v3

      # 4) Prepare the pages directory
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # 5) Upload the entire repository as the artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      # 6) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
